-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgimSVZ2tzo0iz/RdE
4cqVC6s3Nsy8dKcWBCkavEBezyigCgYIKoZIzj0DAQehRANCAASRBlAY/VLNL4Dw
GE20DdxAum4YZxKkbq1ZGz4xPOiELhJmOLceQ7MyBTqX2tXF5WB4er18y+2JwFqk
x4kwKyGZ
-----END PRIVATE KEY-----