package com.forA.chatbot.chat.domain.enums;

public enum ChatStep {
  GENDER,
  BIRTH_YEAR,
  JOB_TYPE,
  DISORDER_TYPE,
  SYMPTOM_TYPE,
  NOTIFICATION_REQUEST,
  EMOTION_SELECT,
  SITUATION_INPUT,
  ACTION_OFFER,
  ACTION_PROPOSE,
  SKILL_SELECT,
  SKILL_CONFIRM,
  ACTION_FEEDBACK,
  CHAT_END
}
